[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "industrial-downtime"
version = "1.0.0"
description = "Industrial downtime analytics"
authors = [{ name = "abdoul" }]
requires-python = ">=3.10"

dependencies = [
    # Web / UI
    "dash>=3.4",
    "dash-bootstrap-components>=2.0",

    # Data
    "pandas>=2.3",
    "numpy>=2.4",
    "fastparquet>=2025.12",

    # Database
    "SQLAlchemy>=2.0",
    "psycopg2-binary>=2.9",

    # Utilities
    "python-dotenv>=1.2",
    "requests>=2.32",

    # Git dependency
    "industrial-downtime @ git+ssh://git@github.com/mounkaila-issoufou/industrial-downtime-analytics.git@2ce1bd0adccea2bae7709c386eddfefe99711e09"
]

[project.optional-dependencies]
dev = [
    "pytest>=9.0",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
industrial-downtime = "industrial_downtime.cli:main"
