[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "industrial-downtime"
version = "1.0.0"
description = "Industrial downtime analytics"
authors = [{ name = "abdoul" }]
requires-python = ">=3.10"

dependencies = [
  "blinker==1.9.0",
  "certifi==2026.1.4",
  "charset-normalizer==3.4.4",
  "click==8.3.1",
  "colorama==0.4.6",
  "cramjam==2.11.0",
  "dash==3.4.0",
  "dash-bootstrap-components==2.0.4",
  "fastparquet==2025.12.0",
  "Flask==3.1.2",
  "fsspec==2026.1.0",
  "greenlet==3.3.1",
  "idna==3.11",
  "importlib_metadata==8.7.1",
  "itsdangerous==2.2.0",
  "Jinja2==3.1.6",
  "MarkupSafe==3.0.3",
  "narwhals==2.15.0",
  "nest-asyncio==1.6.0",
  "numpy==2.4.1",
  "packaging==26.0",
  "pandas==2.3.3",
  "plotly==6.5.2",
  "psycopg2-binary==2.9.11",
  "python-dateutil==2.9.0.post0",
  "pytz==2025.2",
  "requests==2.32.5",
  "retrying==1.4.2",
  "SQLAlchemy==2.0.46",
  "typing_extensions==4.15.0",
  "tzdata==2025.3",
  "urllib3==2.6.3",
  "Werkzeug==3.1.5",
  "zipp==3.23.0"
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
industrial-downtime = "industrial_downtime.cli:main"
